(function(){
  const $=id=>document.getElementById(id);
  let billing={plan:'free',status:'free',is_plus:false};
  async function jsonFetch(url,opts={}){const r=await fetch(url,{cache:'no-store',...opts});let data={};try{data=await r.json();}catch{}if(!r.ok)throw Object.assign(new Error(data.error||'Request failed.'),{status:r.status,data});return data;}
  async function startCheckout(period){try{const data=await jsonFetch('/api/billing/checkout',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({period})});if(data.url)location.href=data.url;}catch(e){if(e.status===401){location.href='/auth/amazon?next='+encodeURIComponent('/app.html?upgrade='+period);return;}const s=$('pricingStatus');if(s)s.textContent=e.message||'Could not start checkout.';else alert(e.message||'Could not start checkout.');}}
  async function openPortal(){try{const data=await jsonFetch('/api/billing/portal',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});if(data.url)location.href=data.url;}catch(e){alert(e.message||'Could not open billing management.');}}
  function showUpgrade(message){if(!document.getElementById('upgradeModal')){const modal=document.createElement('div');modal.id='upgradeModal';modal.className='upgrade-modal';modal.innerHTML='<div class="upgrade-card"><button class="upgrade-close" aria-label="Close">×</button><span class="eyebrow">VineTrack Plus</span><h2>Unlock the full Vine workflow</h2><p id="upgradeMessage"></p><div class="upgrade-actions"><button class="primary-btn" data-up="monthly">£2.99 / month</button><button class="secondary-btn" data-up="annual">£24.99 / year</button></div><small>Secure subscription checkout is handled by Stripe.</small></div>';document.body.appendChild(modal);modal.querySelector('.upgrade-close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show');};modal.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>startCheckout(b.dataset.up));}$('upgradeMessage').textContent=message||'Chrome sync, Review Health, Smart Queue and Review Sessions are included with Plus.';$('upgradeModal').classList.add('show');}
  function applyPlan(){const plus=!!billing.is_plus;document.body.dataset.plan=plus?'plus':'free';const chip=$('planChip');if(chip){chip.textContent=plus?'Plus':'Free';chip.classList.toggle('plus',plus);}const btn=$('billingActionBtn');if(btn){btn.textContent=plus?'Manage plan':'Upgrade';btn.onclick=plus?openPortal:()=>showUpgrade();}document.querySelectorAll('[data-plus-feature]').forEach(el=>el.classList.toggle('plus-locked',!plus));document.querySelectorAll('[data-plus-nav]').forEach(el=>el.classList.toggle('plus-nav-locked',!plus));}
  async function refreshBilling(){try{const data=await jsonFetch('/api/billing/status');billing=data.billing||billing;applyPlan();}catch{}}
  document.addEventListener('click',e=>{const nav=e.target.closest('[data-plus-nav]');if(nav&&!billing.is_plus){e.preventDefault();e.stopImmediatePropagation();showUpgrade('This workflow is available with VineTrack Plus.');}const locked=e.target.closest('[data-plus-feature].plus-locked');if(locked){e.preventDefault();e.stopImmediatePropagation();showUpgrade('Review Health and Smart Queue are included with VineTrack Plus.');}},true);
  document.querySelectorAll('[data-checkout-plan]').forEach(btn=>btn.addEventListener('click',()=>startCheckout(btn.dataset.checkoutPlan)));
  const fb=$('bottomFeedbackBtn');if(fb)fb.onclick=()=>{const nav=document.querySelector('.nav-btn[data-view="feedback"]');if(nav)nav.click();else location.href='/#feedback';};
  const params=new URLSearchParams(location.search);if($('vinetrackAuthData')){try{const auth=JSON.parse($('vinetrackAuthData').textContent||'{}');billing=auth.user?.billing||billing;}catch{}applyPlan();refreshBilling();const upgrade=params.get('upgrade');if(upgrade==='monthly'||upgrade==='annual'){history.replaceState({},'',location.pathname);setTimeout(()=>startCheckout(upgrade),250);}if(params.get('billing')==='success'){history.replaceState({},'',location.pathname);setTimeout(refreshBilling,700);setTimeout(refreshBilling,2200);}}
})();
